const prisma = require("../lib/prisma");
const { getCSTDayBounds } = require("../lib/cstTime");

/**
 * Compiles a report of all daily narratives for a given date.
 */
async function compileDailyNarratives(date = new Date()) {
  const { dayStart, dayEnd } = getCSTDayBounds(date);

  const entries = await prisma.timeEntry.findMany({
    where: {
      clockIn: { gte: dayStart, lte: dayEnd },
      status: "Complete",
      narrative: { not: null },
    },
    include: {
      technician: { select: { name: true } },
    },
    orderBy: { clockIn: "asc" },
  });

  if (entries.length === 0) return null;

  let reportHtml = `
    <h2>Daily Activity Report — ${date.toLocaleDateString('en-US')}</h2>
    <table border="1" cellpadding="8" style="border-collapse: collapse; width: 100%;">
      <thead>
        <tr style="background-color: #f2f2f2;">
          <th>Technician</th>
          <th>Work Order / Task</th>
          <th>Location</th>
          <th>Narrative</th>
          <th>Hours</th>
        </tr>
      </thead>
      <tbody>
  `;

  for (const e of entries) {
    reportHtml += `
      <tr>
        <td><strong>${e.technician.name}</strong></td>
        <td>${e.workOrderLabel || e.taskDescription || "—"}</td>
        <td>${e.jobLocation || "—"}</td>
        <td>${e.narrative}</td>
        <td style="text-align: right;">${e.hoursWorked?.toFixed(2) || "0.00"}</td>
      </tr>
    `;
  }

  reportHtml += `
      </tbody>
    </table>
    <p><em>Generated by Monday Linker Reporting Service</em></p>
  `;

  return reportHtml;
}

/**
 * Sends the daily report to recipients.
 * Placeholder for actual mailing logic (Nodemailer, SendGrid, etc.)
 */
async function sendDailyReport() {
  console.log("[reportingService] Running 8:00 PM CST Daily Report task...");
  
  try {
    const report = await compileDailyNarratives();
    if (!report) {
      console.log("[reportingService] No entries found for today. Skipping report.");
      return;
    }

    // TODO: Fetch recipients from Technicians board or settings
    const recipients = ["gloria@example.com"]; // Placeholder

    console.log("[reportingService] Report compiled. Sending to:", recipients.join(", "));
    // Here logic to send via SMTP/API would go.
    
  } catch (err) {
    console.error("[reportingService] Error generating daily report:", err.message);
  }
}

// Function to initialize CRON if user allows node-cron installation
function initCron() {
  try {
    const cron = require("node-cron");
    // 8:00 PM CST = 2:00 AM UTC (roughly, depends on DST)
    // For CST (UTC-6), it's 02:00 UTC.
    // Crontab: 0 20 * * * in CST
    // We can use timezone option if node-cron supports it
    cron.schedule("0 20 * * *", () => {
      sendDailyReport();
    }, {
      timezone: "America/Chicago"
    });
    console.log("[reportingService] Daily report CRON scheduled for 8:00 PM CST");
  } catch (e) {
    console.warn("[reportingService] node-cron not found. Automatic reporting disabled.");
  }
}

module.exports = {
  compileDailyNarratives,
  sendDailyReport,
  initCron,
};
